#!/usr/bin/env python3
"""Generate docs/workflow-catalog.md from n8n/workflows/*.json (run after changing workflows)."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KIND = {
    "webhook": "Webhook", "code": "Code", "httpRequest": "HTTP", "switch": "Switch",
    "respondToWebhook": "Respond", "emailSend": "Email", "stopAndError": "Stop and error",
    "errorTrigger": "Error trigger", "scheduleTrigger": "Schedule", "noOp": "No-op",
    "emailReadImap": "IMAP trigger", "manualTrigger": "Manual trigger",
}


def describe(node: dict) -> str:
    p = node.get("parameters", {})
    kind = node["type"].split(".")[-1]
    if kind == "httpRequest":
        url = re.sub(r"=?\{\{ \$env\.AI_SERVICE_URL \}\}", "", p.get("url", ""))
        url = re.sub(r"\{\{.*?\}\}", "{id}", url)
        return f"POST `{url}`"
    if kind == "webhook":
        return f"POST `/webhook/{p.get('path')}` (raw body kept for the signature check)"
    if kind == "scheduleTrigger":
        rule = p.get("rule", {}).get("interval", [{}])[0]
        return f"cron `{rule['expression']}`" if "expression" in rule else \
            f"every {rule.get('minutesInterval')} minutes"
    if kind == "switch":
        return f"{p.get('numberOutputs')} outputs: `{p.get('output', '').strip('={} ')}`"
    if kind == "respondToWebhook":
        return f"HTTP {str(p.get('options', {}).get('responseCode')).strip('={} ')}"
    if kind == "code":
        comment = []
        for line in p.get("jsCode", "").splitlines():
            if not line.startswith("//"):
                break
            comment.append(line.lstrip("/ ").strip())
        return " ".join(comment) or "JavaScript"
    if kind == "emailSend":
        return "plain-text email via the SMTP credential"
    if kind == "emailReadImap":
        return f"mailbox `{p.get('mailbox')}`, parsed (`{p.get('format')}`), marked read"
    return ""


def main() -> None:
    out = ["# Workflow catalog", "",
           "Generated by `scripts/workflow_catalog.py` from `n8n/workflows/`. Do not edit by hand.",
           ""]
    for path in sorted((ROOT / "n8n" / "workflows").glob("*.json")):
        wf = json.loads(path.read_text())
        settings = wf.get("settings", {})
        out += [f"## {wf['name']}", "",
                f"File `n8n/workflows/{path.name}` · id `{wf['id']}` · "
                f"{'published' if wf.get('active') else 'not published'}"
                + (f" · errors go to `{settings['errorWorkflow']}`"
                   if settings.get("errorWorkflow") else ""), "",
                "| Node | Type | What it does |", "|---|---|---|"]
        for node in wf["nodes"]:
            kind = KIND.get(node["type"].split(".")[-1], node["type"])
            extra = []
            if node.get("retryOnFail"):
                extra.append(f"retries {node.get('maxTries')}x")
            if node.get("onError") == "continueErrorOutput":
                extra.append("error branch")
            if node.get("executeOnce"):
                extra.append("once")
            text = describe(node) + (f" ({', '.join(extra)})" if extra else "")
            out.append(f"| {node['name']} | {kind} | {text.replace('|', '/')} |")
        out.append("")
    (ROOT / "docs" / "workflow-catalog.md").write_text("\n".join(out))
    print("wrote docs/workflow-catalog.md")


if __name__ == "__main__":
    main()
